import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sads.finztrust.com/admin/login');
  await page.getByRole('textbox', { name: 'ឈ្មោះអ្នកប្រើប្រាស់*' }).fill('admin');
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).click();
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).fill('password123');
  await page.getByRole('button', { name: 'ចូលក្នុងប្រព័ន្ធ' }).click();
  await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  await page.getByRole('button', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  await page.locator('#fi-wRzKVQTFiwTDvmDuQFtG-action-0').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  await page.getByRole('textbox', { name: 'ឈ្មោះក្រុម (ឧទាហរណ៍៖ ក្រុមទី១...)' }).fill('group 1');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('textbox', { name: 'កាលបរិច្ឆេទដាក់ពិន្ទុ*' }).click();
  await page.getByRole('option', { name: '2', exact: true }).click();
  await page.getByRole('option', { name: '2', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលរួម*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលរួម*' }).fill('30');
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).click();
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ស្រ្តី*' }).click();
  await page.getByRole('spinbutton', { name: 'ស្រ្តី*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).click();
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).fill('4');
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).click();
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).click();
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ជនជាតិភាគតិច*' }).click();
  await page.getByRole('spinbutton', { name: 'ជនជាតិភាគតិច*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).click();
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'គ្រួសារក្រីក្រ*' }).click();
  await page.getByRole('spinbutton', { name: 'គ្រួសារក្រីក្រ*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ជនពិការ*' }).click();
  await page.getByRole('spinbutton', { name: 'ជនពិការ*' }).fill('0');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('button', { name: 'បន្ថែមថ្មី' }).click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).fill('ទឹកស្អាតប្រើប្រាស់');
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.getByText('HC19 ទឹកស្អាតប្រើប្រាស់').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('5');
  await page.getByRole('button', { name: 'បន្ថែមថ្មី' }).click();
  await page.locator('[id="form.data::wizard.jhaand2::data::wizard-step.span-classtext-1e3a8a-darktext-blue-400-font-bold-text-18pxjhaand2-knntlkkhnnavncchyspan::data::section.brainstorming_data.d6c963ea-3d1b-432b-b111-790c9b630127.brainstorm_text"]').click();
  await page.locator('[id="form.data::wizard.jhaand2::data::wizard-step.span-classtext-1e3a8a-darktext-blue-400-font-bold-text-18pxjhaand2-knntlkkhnnavncchyspan::data::section.brainstorming_data.d6c963ea-3d1b-432b-b111-790c9b630127.brainstorm_text"]').fill('អនាម័យ ឫបរិស្ថាន');
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.locator('[id="form.data::wizard.jhaand2::data::wizard-step.span-classtext-1e3a8a-darktext-blue-400-font-bold-text-18pxjhaand2-knntlkkhnnavncchyspan::data::section.brainstorming_data.d6c963ea-3d1b-432b-b111-790c9b630127.brainstorm_text"]').click();
  await page.locator('[id="form.data::wizard.jhaand2::data::wizard-step.span-classtext-1e3a8a-darktext-blue-400-font-bold-text-18pxjhaand2-knntlkkhnnavncchyspan::data::section.brainstorming_data.d6c963ea-3d1b-432b-b111-790c9b630127.brainstorm_text"]').fill('អនាម័យ');
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.getByRole('option', { name: 'HC02 អនាម័យ ឬបរិស្ថាន' }).click();
  await page.getByRole('option', { name: 'HC02 អនាម័យ ឬបរិស្ថាន' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Brainstorm text Indicator id HC02 អនាម័យ ឬបរិស្ថានHC02 អនាម័យ ឬបរិស្ថាន' }).getByRole('spinbutton').click();
  await page.getByRole('listitem').filter({ hasText: 'Brainstorm text Indicator id HC02 អនាម័យ ឬបរិស្ថានHC02 អនាម័យ ឬបរិស្ថាន' }).getByRole('spinbutton').fill('4');
});