import { test, expect } from '@playwright/test';

//pass

test('test', async ({ page }) => {
  test.setTimeout(10 * 60 * 1000);
  await page.goto('https://sads.finztrust.com/admin/login');

  await page.getByRole('textbox', { name: 'ឈ្មោះអ្នកប្រើប្រាស់*' }).fill('admin');
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).click();
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).fill('password123');
  await page.getByRole('button', { name: 'ចូលក្នុងប្រព័ន្ធ' }).click();

  //Sevice provider
  // await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  // await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  // await page.getByRole('table').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ អ្នកផ្តល់សេវា' }).click();

  //Citizen
  // await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  // await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  // await page.getByRole('button', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  // await page.getByRole('dialog').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  // await page.getByRole('textbox', { name: 'ឈ្មោះក្រុម (ឧទាហរណ៍៖ ក្រុមទី១...)' }).fill('group 1');
  // await page.getByRole('button', { name: 'បន្ទាប់' }).click();

    //Vulnerable group
  await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  await page.getByRole('button', { name: 'បណ្ណដាក់ពិន្ទុ ក្រុមជនងាយរងគ្រោះ' }).click();
  await page.getByRole('dialog').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ ក្រុមជនងាយរងគ្រោះ' }).click();
  await page.getByRole('textbox', { name: 'ឈ្មោះក្រុម (ឧទាហរណ៍៖ ក្រុមទី១...)' }).fill('group 1');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();

  await page.getByRole('textbox', { name: 'កាលបរិច្ឆេទដាក់ពិន្ទុ*' }).click();
  await page.getByRole('option', { name: '20' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលសរុប*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលសរុប*' }).fill('30');
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).click();
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចំនួនស្រ្តី*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនស្រ្តី*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).click();
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).click();
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).click();
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).fill('2');
  await page.getByRole('spinbutton', { name: 'ចំនួនជនជាតិភាគតិច*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនជនជាតិភាគតិច*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).click();
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).fill('0');
  await page.getByRole('spinbutton', { name: 'ចំនួនគ្រួសារក្រីក្រ*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនគ្រួសារក្រីក្រ*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចំនួនជនពិការ*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនជនពិការ*' }).fill('0');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.getByRole('option', { name: 'HC40 ឯកសណ្ថាន' }).click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).press('Alt+e');
  await page.getByRole('textbox', { name: 'Brainstorm text' }).fill('ឯកសណ្ថាន');
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^HC05\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(1).fill('ឡដុតសម្រាម');
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^HC06\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(2).fill('សេវាសង្រ្គោះបន្ទាន់');
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^HC38\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(3).fill('កន្លែងដាក់ កង់ ម៉ូតូ ឡាន');
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^HC37\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(4).fill('កន្លែងរង់ចាំ');
  await page.locator('li:nth-child(5) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.locator('body').press('AudioVolumeDown');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'ដំណើរការដាក់ពិន្ទុ' }).click();
  const page1 = await page1Promise;
  await page1.locator('label').nth(2).click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(2) > .rating-label').click();
  await page1.locator('div:nth-child(4) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(2) > .rating-label').click();
  await page1.locator('div:nth-child(6) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.getByRole('link', { name: 'បន្ថែមការដាក់ពិន្ទុ' }).click();
  await page1.locator('label').nth(3).click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(4) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(6) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.getByRole('button', { name: 'បញ្ជូន' }).click();
  await page1.getByRole('link', { name: 'បន្ថែមការដាក់ពិន្ទុ' }).click();
  await page1.locator('label').first().click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(2) > .rating-label').click();
  await page1.locator('div:nth-child(4) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.getByRole('button', { name: 'បញ្ជូន' }).click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.locator('div:nth-child(6) > .grid > div:nth-child(5) > .rating-label').click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.getByRole('button', { name: 'បញ្ឈប់ការដាក់ពិន្ទុ' }).click();
  await page1.getByRole('link', { name: 'យល់ព្រម' }).click();
  await page.getByRole('button', { name: 'បាទ/ចាស' }).click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC40 - ឯកសណ្ថាន 3' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC40 - ឯកសណ្ថាន 3' }).getByPlaceholder('ចំណុចខ្លាំង').fill('ឯកសណ្ថាន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC40 - ឯកសណ្ថាន 3' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC40 - ឯកសណ្ថាន 3' }).getByPlaceholder('ចំណុចខ្សោយ').fill('ឯកសណ្ថាន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC40 - ឯកសណ្ថាន 3' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC40 - ឯកសណ្ថាន 3' }).getByPlaceholder('មតិយោបល់').fill('ឯកសណ្ថាន');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').first().click();
  await page.locator('.search-container').first().click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ឯ');
  await page.getByRole('dialog').getByText('HC40 - ឯកសណ្ថាន').click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.getByRole('combobox').first().selectOption('1');
  await page.getByRole('combobox').nth(1).selectOption('5');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC05 - ឡដុតសម្រាម 4' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC05 - ឡដុតសម្រាម 4' }).getByPlaceholder('ចំណុចខ្លាំង').fill('ឡដុតសម្រាម');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC05 - ឡដុតសម្រាម 4' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC05 - ឡដុតសម្រាម 4' }).getByPlaceholder('ចំណុចខ្សោយ').fill('ឡដុតសម្រាម');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC05 - ឡដុតសម្រាម 4' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC05 - ឡដុតសម្រាម 4' }).getByPlaceholder('មតិយោបល់').fill('ឡដុតសម្រាម');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(1).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ឡ');
  await page.getByRole('dialog').getByText('HC05 - ឡដុតសម្រាម').click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.getByRole('combobox').nth(2).selectOption('5');
  await page.getByRole('combobox').nth(3).selectOption('6');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC06' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC06' }).getByPlaceholder('ចំណុចខ្លាំង').fill('សេវាសង្រ្គោះបន្ទាន់');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC06' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC06' }).getByPlaceholder('ចំណុចខ្សោយ').fill('សេវាសង្រ្គោះបន្ទាន់');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC06' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC06' }).getByPlaceholder('មតិយោបល់').fill('សេវាសង្រ្គោះបន្ទាន់');
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div > div > .search-input').first().click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ស');
  await page.getByRole('dialog').getByText('HC06 - សេវាសង្រ្គោះបន្ទាន់').click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.getByRole('combobox').nth(4).selectOption('5');
  await page.getByRole('combobox').nth(5).selectOption('7');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('ចំណុចខ្លាំង').fill('កន្លែងដាក់ កង់ ម៉ូតូ ឡាន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('ចំណុចខ្លាំង').press('AudioVolumeDown');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('ចំណុចខ្សោយ').fill('កន្លែងដាក់ កង់ ម៉ូតូ ឡាន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('ចំណុចខ្សោយ').press('AudioVolumeDown');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC38' }).getByPlaceholder('មតិយោបល់').fill('កន្លែងដាក់ កង់ ម៉ូតូ ឡាន');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(3).click();
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > .premium-modal > div:nth-child(2) > .search-container').click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ក');
  await page.getByRole('dialog').getByText('HC38 - កន្លែងដាក់ កង់ ម៉ូតូ ឡាន').click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(2) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('5');
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(3) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('2');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC37 - កន្លែងរង់ចាំ 2' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC37 - កន្លែងរង់ចាំ 2' }).getByPlaceholder('ចំណុចខ្លាំង').fill('កន្លែងរង់ចាំ');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC37 - កន្លែងរង់ចាំ 2' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC37 - កន្លែងរង់ចាំ 2' }).getByPlaceholder('ចំណុចខ្សោយ').fill('កន្លែងរង់ចាំ');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC37 - កន្លែងរង់ចាំ 2' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក HC37 - កន្លែងរង់ចាំ 2' }).getByPlaceholder('មតិយោបល់').fill('កន្លែងរង់ចាំ');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(4).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ក');
  await page.getByRole('dialog').getByText('HC37 - កន្លែងរង់ចាំ').click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.locator('li:nth-child(5) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(2) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('1');
  await page.locator('li:nth-child(5) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(3) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('2');
  await page.getByRole('button', { name: 'បញ្ចប់' }).click();
  await page.getByRole('button', { name: 'យល់ព្រម' }).click();
});