import { test, expect } from '@playwright/test';

//pass

test('test', async ({ page }) => {
  test.setTimeout(10 * 60 * 1000);
  await page.goto('https://sads.finztrust.com/admin/login');
  await page.getByRole('textbox', { name: 'ឈ្មោះអ្នកប្រើប្រាស់*' }).fill('admin');
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).click();
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).fill('password123');
  await page.getByRole('button', { name: 'ចូលក្នុងប្រព័ន្ធ' }).click();
  
  //Sevice provider
  // await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  // await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  // await page.getByRole('table').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ អ្នកផ្តល់សេវា' }).click();

  //Citizen
  await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  await page.getByRole('button', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  await page.getByRole('dialog').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  await page.getByRole('textbox', { name: 'ឈ្មោះក្រុម (ឧទាហរណ៍៖ ក្រុមទី១...)' }).fill('group 1');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();

  //Vulnerable group
  // await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  // await page.getByRole('button', { name: 'បង្កើតទម្រង់ដាក់ពិន្ទុ' }).first().click();
  // await page.getByRole('button', { name: 'បណ្ណដាក់ពិន្ទុ ក្រុមជនងាយរងគ្រោះ' }).click();
  // await page.getByRole('dialog').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ ក្រុមជនងាយរងគ្រោះ' }).click();
  // await page.getByRole('textbox', { name: 'ឈ្មោះក្រុម (ឧទាហរណ៍៖ ក្រុមទី១...)' }).fill('group 1');
  // await page.getByRole('button', { name: 'បន្ទាប់' }).click();


  await page.getByRole('textbox', { name: 'កាលបរិច្ឆេទដាក់ពិន្ទុ*' }).click();
  await page.getByRole('option', { name: '20' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលសរុប*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលសរុប*' }).fill('30');
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).click();
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចំនួនស្រ្តី*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនស្រ្តី*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).click();
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).click();
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).click();
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចំនួនជនជាតិភាគតិច*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនជនជាតិភាគតិច*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).click();
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).fill('0');
  await page.getByRole('spinbutton', { name: 'ចំនួនគ្រួសារក្រីក្រ*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនគ្រួសារក្រីក្រ*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចំនួនជនពិការ*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនជនពិការ*' }).fill('0');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.getByRole('option', { name: 'PS39 កន្លែងលាងដៃ' }).click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).fill('កន្លែងលាងដៃ');
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('.custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^PS45\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(1).fill('ការបង្រៀន');
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^PS17\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(2).fill('ធុងសម្រាម');
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(3) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^PS06\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(3).fill('សៀវភៅសិក្សាគោល');
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ថែមជួរថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).last().click();
  await page.locator('[id^="fi-select-input-option-"]:visible').filter({ hasText: /^PS02\b/ }).first().click();
  await page.getByRole('textbox', { name: 'Brainstorm text' }).nth(4).fill('អនាម័យ និងបរិស្ថាន');
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > div > div > div > .items-end > .fi-sc > div:nth-child(2) > .fi-sc-component > .custom-scoring-container-wrapper > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'ដំណើរការដាក់ពិន្ទុ' }).click();
  const page1 = await page1Promise;
  await page1.locator('label').first().click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(2) > .rating-label').click();
  await page1.locator('div:nth-child(4) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.locator('div:nth-child(6) > .grid > div:nth-child(5) > .rating-label').click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.getByRole('link', { name: 'បន្ថែមការដាក់ពិន្ទុ' }).click();
  await page1.locator('label').nth(4).click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.locator('div:nth-child(4) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(2) > .rating-label').click();
  await page1.locator('div:nth-child(6) > .grid > div > .rating-label').first().click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.getByRole('link', { name: 'បន្ថែមការដាក់ពិន្ទុ' }).click();
  await page1.locator('label').nth(1).click();
  await page1.locator('div:nth-child(3) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(4) > .grid > div:nth-child(4) > .rating-label').click();
  await page1.locator('div:nth-child(5) > .grid > div:nth-child(3) > .rating-label').click();
  await page1.locator('div:nth-child(6) > .grid > div:nth-child(2) > .rating-label').click();
  await page1.locator('form div').filter({ hasText: 'បញ្ជូន' }).click();
  await page1.getByRole('button', { name: 'បញ្ឈប់ការដាក់ពិន្ទុ' }).click();
  await page1.getByRole('link', { name: 'យល់ព្រម' }).click();
  await page.getByRole('button', { name: 'បាទ/ចាស' }).click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS39 - កន្លែងលាងដៃ 3' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS39 - កន្លែងលាងដៃ 3' }).getByPlaceholder('ចំណុចខ្លាំង').fill('កន្លែងលាងដៃ');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS39 - កន្លែងលាងដៃ 3' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS39 - កន្លែងលាងដៃ 3' }).getByPlaceholder('ចំណុចខ្សោយ').fill('កន្លែងលាងដៃ');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS39 - កន្លែងលាងដៃ 3' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS39 - កន្លែងលាងដៃ 3' }).getByPlaceholder('មតិយោបល់').fill('កន្លែងលាងដៃ');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').first().click();
  await page.locator('.search-container').first().click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ក');
  await page.getByRole('dialog').getByText('PS39 - កន្លែងលាងដៃ').click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.getByRole('combobox').first().selectOption('1');
  await page.getByRole('combobox').nth(1).selectOption('1');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS45 - ការបង្រៀន 3' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS45 - ការបង្រៀន 3' }).getByPlaceholder('ចំណុចខ្លាំង').fill('ការបង្រៀន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS45 - ការបង្រៀន 3' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS45 - ការបង្រៀន 3' }).getByPlaceholder('ចំណុចខ្សោយ').fill('ការបង្រៀន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS45 - ការបង្រៀន 3' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS45 - ការបង្រៀន 3' }).getByPlaceholder('មតិយោបល់').fill('ការបង្រៀន');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(1).click();
  await page.locator('li:nth-child(2) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > .premium-modal > div:nth-child(2) > .search-container').click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ការបង្រៀន');
  await page.locator('.premium-modal:visible > div:nth-child(2) > div:nth-child(2) > div').filter({ hasText: 'ការបង្រៀន' }).first().click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.getByRole('combobox').nth(2).selectOption('1');
  await page.getByRole('combobox').nth(3).selectOption('3');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS17 - ធុងសម្រាម 3' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS17 - ធុងសម្រាម 3' }).getByPlaceholder('ចំណុចខ្លាំង').fill('ធុងសម្រាម');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS17 - ធុងសម្រាម 3' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS17 - ធុងសម្រាម 3' }).getByPlaceholder('ចំណុចខ្សោយ').fill('ធុងសម្រាម');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS17 - ធុងសម្រាម 3' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS17 - ធុងសម្រាម 3' }).getByPlaceholder('មតិយោបល់').fill('ធុងសម្រាម');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(2).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('ធុងសម្រាម');
  await page.locator('.premium-modal:visible > div:nth-child(2) > div:nth-child(2) > div').filter({ hasText: 'ធុងសម្រាម' }).first().click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.getByRole('combobox').nth(4).selectOption('1');
  await page.getByRole('combobox').nth(5).selectOption('4');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS06 - សៀវភៅសិក្សាគោល 3' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS06 - សៀវភៅសិក្សាគោល 3' }).getByPlaceholder('ចំណុចខ្លាំង').fill('សៀវភៅសិក្សាគោល');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS06 - សៀវភៅសិក្សាគោល 3' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS06 - សៀវភៅសិក្សាគោល 3' }).getByPlaceholder('ចំណុចខ្សោយ').fill('សៀវភៅសិក្សាគោល');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS06 - សៀវភៅសិក្សាគោល 3' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS06 - សៀវភៅសិក្សាគោល 3' }).getByPlaceholder('មតិយោបល់').fill('សៀវភៅសិក្សាគោល');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(3).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('សៀវភៅសិក្សាគោល');
  await page.locator('.premium-modal:visible > div:nth-child(2) > div:nth-child(2) > div').filter({ hasText: 'សៀវភៅសិក្សាគោល' }).first().click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(2) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('1');
  await page.locator('li:nth-child(4) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(3) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('2');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS02' }).getByPlaceholder('ចំណុចខ្លាំង').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS02' }).getByPlaceholder('ចំណុចខ្លាំង').fill('អនាម័យ និងបរិស្ថាន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS02' }).getByPlaceholder('ចំណុចខ្សោយ').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS02' }).getByPlaceholder('ចំណុចខ្សោយ').fill('អនាម័យ និងបរិស្ថាន');
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS02' }).getByPlaceholder('មតិយោបល់').click();
  await page.getByRole('listitem').filter({ hasText: 'ជ្រើសរើសចម្លើយស្ដង់ដារ បញ្ចូលថ្មី៖ "" បោះបង់ រក្សាទុក PS02' }).getByPlaceholder('មតិយោបល់').fill('អនាម័យ និងបរិស្ថាន');
  await page.getByText('ស្វែងរក ឬបញ្ចូល').nth(4).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).click();
  await page.getByRole('textbox', { name: 'ស្វែងរក ឬបញ្ចូលចម្លើយថ្មី' }).fill('អនាម័យ និងបរិស្ថាន');
  await page.locator('.premium-modal:visible > div:nth-child(2) > div:nth-child(2) > div').filter({ hasText: 'អនាម័យ និងបរិស្ថាន' }).first().click();
  await page.getByRole('button', { name: 'រក្សាទុក' }).click();
  await page.locator('li:nth-child(5) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(2) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('1');
  await page.locator('li:nth-child(5) > .fi-fo-repeater-item-content > .fi-sc > .fi-grid-col.lg\\:fi-grid-col-span > .fi-sc-component > .form-row > div:nth-child(7) > div:nth-child(3) > .items-wrap > .item-row > .dropdown-wrap > .dropdown-select').selectOption('2');
  await page.getByRole('button', { name: 'បញ្ចប់' }).click();
  await page.getByRole('button', { name: 'យល់ព្រម' }).click();
});