import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sads.finztrust.com/admin/login');
  await page.getByRole('textbox', { name: 'ឈ្មោះអ្នកប្រើប្រាស់*' }).fill('cafkp1');
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).click();
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).fill('');
  await page.getByRole('textbox', { name: 'ឈ្មោះអ្នកប្រើប្រាស់*' }).click();
  await page.getByRole('textbox', { name: 'ឈ្មោះអ្នកប្រើប្រាស់*' }).fill('cafkp1');
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).click();
  await page.getByRole('textbox', { name: 'ពាក្យសម្ងាត់*' }).fill('cafkp1123');
  await page.getByRole('button', { name: 'ចូលក្នុងប្រព័ន្ធ' }).click();
  await page.getByRole('link', { name: 'ការពិនិត្យវាយតម្លៃអំពីលទ្ធផលការងារ' }).click();
  await page.getByRole('button', { name: 'គ្រប់គ្រងបណ្ណដាក់ពិន្ទុ' }).click();
  await page.getByRole('button', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  await page.getByRole('dialog').getByRole('link', { name: 'បណ្ណដាក់ពិន្ទុ ប្រជាពលរដ្ឋ' }).click();
  await page.getByRole('textbox', { name: 'ឈ្មោះក្រុម (ឧទាហរណ៍៖ ក្រុមទី១...)' }).fill('group 1');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('textbox', { name: 'កាលបរិច្ឆេទដាក់ពិន្ទុ*' }).click();
  await page.getByRole('option', { name: '9', exact: true }).click();
  await page.getByRole('option', { name: '9', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលរួមសរុប*' }).click();
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលរួមសរុប*' }).fill('30');
  await page.getByRole('spinbutton', { name: 'ចំនួនអ្នកចូលរួមសរុប*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'យុវជន*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'ស្រ្តី*' }).fill('6');
  await page.getByRole('spinbutton', { name: 'ស្រ្តី*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'ចាស់ជរា*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).fill('4');
  await page.getByRole('spinbutton', { name: 'កុមារា*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).fill('5');
  await page.getByRole('spinbutton', { name: 'កុមារី*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'ជនជាតិភាគតិច*' }).fill('3');
  await page.getByRole('spinbutton', { name: 'ជនជាតិភាគតិច*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).fill('8');
  await page.getByRole('spinbutton', { name: 'ជនជាតិដើមភាគតិច*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'គ្រួសារក្រីក្រ*' }).fill('6');
  await page.getByRole('spinbutton', { name: 'គ្រួសារក្រីក្រ*' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'ជនមានពិការភាព*' }).fill('8');
  await page.getByRole('spinbutton', { name: 'ជនមានពិការភាព*' }).press('Enter');
  await page.getByRole('button', { name: 'បន្ទាប់' }).click();
  await page.getByRole('button', { name: 'បន្ថែមថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ', exact: true }).click();
  await page.getByText('HC37 កន្លែងរង់ចាំ').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('5');
  await page.getByRole('button', { name: 'បន្ថែមថ្មី' }).click();
  await page.getByRole('button', { name: 'បន្ថែមថ្មី' }).click();
  await page.getByRole('button', { name: 'ជ្រើសរើសលក្ខណៈវិនិច្ឆ័យ' }).nth(1).click();
});